Repository rh-messaging/amq-streams-docs, pull requests merged in 2019-10, with the labels that each got.

#59 New Kafka Exporter section
  books/assembly-getting-started.adoc
  books/assembly-kafka-exporter.adoc
  books/common/attributes.adoc
  books/kafka-exporter/con-kafka-exporter-alerts.adoc
  books/kafka-exporter/con-kafka-exporter-grafana.adoc
  books/kafka-exporter/con-kafka-exporter-lag.adoc
  books/kafka-exporter/proc-kafka-exporter-running.adoc
  books/kafka-exporter/ref-kafka-exporter-metrics.adoc
  books/master.adoc
Labels: documentation, peer review needed, sme review needed

#60 [DOC] Create Kafka Bridge quick start
  .gitignore
  books/assembly-kafka-bridge-concepts.adoc
  books/assembly-kafka-bridge-overview.adoc
  books/assembly-kafka-bridge-quickstart.adoc
  books/assembly-using-the-kafka-bridge.adoc
  books/common/attributes.adoc
  books/con-loggers-kafka-bridge.adoc
  books/con-requests-kafka-bridge.adoc
  books/con-sending-requests-to-kafka-bridge.adoc
  books/master.adoc
  books/proc-bridge-committing-consumer-offsets-to-log.adoc
  books/proc-bridge-deleting-consumer.adoc
  books/proc-bridge-retrieving-latest-messages-from-consumer.adoc
  books/proc-bridge-seeking-offsets-for-partition.adoc
  books/proc-bridge-subscribing-consumer-topics.adoc
  books/proc-configuring-kafka-bridge.adoc
  books/proc-creating-kafka-bridge-consumer.adoc
  books/proc-deploying-kafka-bridge-quickstart.adoc
  books/proc-downloading-kafka-bridge.adoc
  books/proc-installing-kafka-bridge.adoc
  books/proc-producing-messages-from-bridge-topics-partitions.adoc
  books/proc-running-single-node-amq-streams-cluster.adoc
  books/ref-api-resources-kafka-bridge.adoc
Labels: documentation, peer review done, ready for merge, sme review done

#62 Use KAFKA_OPTS instead of EXTRA_ARGS for Zookeeper SASL configuration
  .gitignore
  books/con-zookeeper-sasl-authentication.adoc
  books/proc-zookeeper-enable-client-to-server-auth-digest-md5.adoc
  books/proc-zookeeper-enable-server-to-server-auth-digest-md5.adoc
Labels: documentation, peer review done
