Repository rh-messaging/amq-streams-docs, pull requests merged in 2019-11, with the labels that each got.

#64 [DOC] Distributed tracing chapter
  .travis/check_docs.sh
  books/assembly-distributed-tracing.adoc
  books/assembly-instrumenting-kafka-clients-components-tracers.adoc
  books/assembly-setting-up-tracing-kafka-clients.adoc
  books/common/attributes.adoc
  books/images/image_con-overview-distributed-tracing.png
  books/master.adoc
  books/tracing/con-overview-distributed-tracing.adoc
  books/tracing/proc-configuring-jaeger-tracer-kafka-clients.adoc
  books/tracing/proc-instrumenting-kafka-streams-with-tracers.adoc
  books/tracing/proc-instrumenting-mirror-maker-connect-for-tracing.adoc
  books/tracing/proc-instrumenting-producers-consumers-opentracing.adoc
  books/tracing/ref-tracing-environment-variables.adoc
Labels: documentation, sme review done

#65 Make ZooKeeper references consistent
  books/assembly-configuring-zookeeper-authentication.adoc
  books/assembly-configuring-zookeeper.adoc
  books/assembly-getting-started.adoc
  books/assembly-kafka-zookeeper-authentication.adoc
  books/assembly-kafka-zookeeper-authorization.adoc
  books/assembly-monitoring.adoc
  books/assembly-overview.adoc
  books/common/attributes.adoc
  books/con-considerations-for-data-storage.adoc
  books/con-important-broker-metrics.adoc
  books/con-kafka-authentication.adoc
  books/con-kafka-zookeeper-authentication-jaas.adoc
  books/con-kafka-zookeeper-authorization-enabling-acls.adoc
  books/con-kafka-zookeeper-configuration.adoc
  books/con-monitoring-using-jconsole.adoc
  books/con-reassignment-of-partitions.adoc
  books/con-zookeeeper-cluster-configuration.adoc
  books/con-zookeeper-authorization.adoc
  books/con-zookeeper-basic-configuration.adoc
  books/con-zookeeper-logging.adoc
  books/con-zookeeper-sasl-authentication.adoc
  books/con-zookeeper-tls.adoc
  books/proc-configuring-amq-streams.adoc
  books/proc-creating-a-topic.adoc
  books/proc-deleting-a-topic.adoc
  books/proc-describing-a-topic.adoc
  books/proc-installing-amq-streams.adoc
  books/proc-kafka-adding-scram-users.adoc
  books/proc-kafka-authorization-add-rules.adoc
  books/proc-kafka-deleting-scram-users.adoc
  books/proc-kafka-enable-zookeeper-auth.adoc
  books/proc-kafka-enabling-zookeeper-acls.adoc
  books/proc-kafka-migrating-zookeeper-acls.adoc
  books/proc-modifying-a-topic.adoc
  books/proc-running-multinode-kafka-cluster.adoc
  books/proc-running-multinode-zookeeper-cluster.adoc
  books/proc-running-single-node-amq-streams-cluster.adoc
  books/proc-stopping-amq-streams.adoc
  books/proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc
  books/proc-updating-kafka-brokers-to-new-message-format-version.adoc
  books/proc-upgrading-clients-to-new-kafka-version.adoc
  books/proc-upgrading-zookeeper-binaries.adoc
  books/proc-using-amq-streams.adoc
  books/proc-zookeeper-enable-client-to-server-auth-digest-md5.adoc
  books/proc-zookeeper-enable-server-to-server-auth-digest-md5.adoc
  books/ref-broker-config.adoc
  books/ref-kafka-versions.adoc
  books/ref-zookeeper-additional-configuration.adoc
  books/snip-kafka-versions.adoc
  books/snip-reassign-partitions.adoc
Labels: documentation, peer review done, sme review needed

#66 [DOC] How to enable distributed tracing in Kafka Bridge
  books/assembly-configuring-mirrormaker-kafka-connect-tracing.adoc
  books/assembly-distributed-tracing.adoc
  books/assembly-instrumenting-kafka-clients-components-tracers.adoc
  books/assembly-kafka-bridge-concepts.adoc
  books/assembly-setting-up-tracing-kafka-clients.adoc
  books/common/attributes.adoc
  books/proc-configuring-kafka-bridge.adoc
  books/tracing/con-overview-distributed-tracing.adoc
  books/tracing/proc-configuring-jaeger-tracer-kafka-clients.adoc
  books/tracing/proc-enabling-tracing-for-kafka-bridge.adoc
  books/tracing/proc-enabling-tracing-for-kafka-connect.adoc
  books/tracing/proc-enabling-tracing-for-mirrormaker.adoc
  books/tracing/proc-instrumenting-kafka-streams-with-tracers.adoc
  books/tracing/proc-instrumenting-mirror-maker-connect-for-tracing.adoc
  books/tracing/proc-instrumenting-producers-consumers-tracing.adoc
  books/tracing/ref-tracing-environment-variables.adoc
Labels: documentation, peer review done, sme review done

#67 New architecture graphic and updated intro
  books/assembly-overview.adoc
  books/common/attributes.adoc
  books/images/AMQ_Streams_478987_0918_01.png
  books/images/amq-streams-architecture.png
Labels: documentation, peer review done, sme review needed
