Repository rh-messaging/amq-streams-docs, pull requests merged in 2019-03, with the labels that each got.

#39 Bump the Red Hat serial number for Maven dependencies
  books/common/attributes.adoc
Labels: documentation, peer review needed

#40 [DOC] Procedure for upgrading AMQ Streams on RHEL
  books/assembly-overview.adoc
  books/assembly-upgrade-1-1-0.adoc
  books/common/attributes.adoc
  books/con-strategies-for-upgrading-clients.adoc
  books/master.adoc
  books/proc-installing-amq-streams.adoc
  books/proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc
  books/proc-updating-kafka-brokers-to-new-message-format-version.adoc
  books/proc-updating-zookeeper-binaries.adoc
  books/proc-upgrading-clients-to-new-kafka-version.adoc
  books/proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc
Labels: documentation, peer review needed, sme review needed

#41 [DOC] New and modified content for ENTMQST-555
  books/con-considerations-for-data-storage.adoc
Labels: peer review done

#42 Move Storage considerations section
  books/assembly-getting-started.adoc
  books/assembly-overview.adoc
  books/con-considerations-for-data-storage.adoc
Labels: documentation, peer review needed

#43 [DOC] Updates to the upgrade chapter [ENTMQST-781]
  books/assembly-upgrade-1-1-0.adoc
  books/con-strategies-for-upgrading-clients.adoc
  books/proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc
  books/proc-updating-kafka-brokers-to-new-message-format-version.adoc
  books/proc-updating-zookeeper-binaries.adoc
  books/proc-upgrading-clients-to-new-kafka-version.adoc
  books/proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc
Labels: documentation, peer review needed, sme review needed

#44 [DOC] RHEL upgrade - Prereq updates - ENTMQST 781
  books/assembly-upgrade-1-1-0.adoc
  books/proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc
  books/proc-updating-kafka-brokers-to-new-message-format-version.adoc
  books/proc-updating-zookeeper-binaries.adoc
  books/proc-upgrading-clients-to-new-kafka-version.adoc
  books/proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc
  books/ref-overview-document-conventions.adoc
  books/ref-overview-key-features.adoc
  books/ref-overview-supported-configurations.adoc
Labels: documentation, peer review needed, sme review done

#45 Removed the v1.1.0 specific attribute.
  books/common/attributes.adoc
  books/proc-downloading-amq-streams.adoc
  books/proc-updating-zookeeper-binaries.adoc
  books/proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc
Labels: documentation

#46 Added books/build/** to the gitignore file
  .gitignore
Labels: documentation
